name: "New Icon Request"
description: "Submit requests for missing icons for TV-compatible applications."
title: "Icon Request:"
labels: ["Icon request"]
body:
  - type: input
    id: app_names
    attributes:
      label: "Application Names"
      description: "Enter the names of the applications you want icons for, separated by commas."
      placeholder: "YouTube, Netflix, Prime Video"
    validations:
      required: true

  - type: textarea
    id: app_links
    attributes:
      label: "Application Links"
      description: "Provide links to the requested applications."
    validations:
      required: true

  - type: input
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Optional: Any extra details about the icon requests."
    validations:
      required: false

  - type: textarea
    id: icon_examples
    attributes:
      label: "Icon Examples"
      description: "Upload or paste example images of the icons for the requested applications."
    validations:
      required: false
