name: "Icon mapping issue report"
description: "Submit a report if any supported icons in the pack are not being automatically assigned to their applications. Please note that support can only be provided for Android/Google TV devices."
title: "Icon mapping report:"
labels: ["Icon mapping"]
body:
  - type: input
    id: app_names
    attributes:
      label: "Application Names"
      description: "Enter the names of the applications you want icons for, separated by commas."
      placeholder: "YouTube, Netflix, Prime Video"

  - type: input
    id: device_type
    attributes:
      label: "Device Type"
      description: "Specify the device type you are using."
      placeholder: "Example: Chromecast with Google TV, NVIDIA Shield, onn 4k pro"

  - type: input
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Optional: Any extra details that may be helpful."

  - type: markdown
    attributes:
      value: "**Make sure you are running the latest version of the icon pack and have restarted your device before submitting an issue report.**"
