name: "Icon Request"
description: "Submit requests for missing icons for TV-compatible applications."
title: "Icon Request:"
labels: ["icon request"]
body:
  - type: textarea
    id: app_names
    attributes:
      label: "Application Names"
      description: "Enter the names of the applications you want icons for, one per line. Example: YouTube"
      placeholder: |
        YouTube
        Netflix
        Prime Video

  - type: textarea
    id: package_names
    attributes:
      label: "Package Names"
      description: "Leave blank if you don't know the package names. Enter the package names corresponding to the applications above, one per line in the same order. Example: com.google.android.youtube"
      placeholder: |
        com.google.android.youtube
        com.netflix.mediaclient
        com.amazon.avod.thirdpartyclient

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Optional: Any extra details about the icon requests."
