name: "Icon Request"
description: "Submit requests for missing icons for TV-compatible applications."
title: "Icon Request: enter application names here"
labels: ["icon request"]
body:
  - type: textarea
    id: application_list
    attributes:
      label: "Applications / Package Names"
      description: "List all applications or package names you want icons for, one per line. Example: com.example.app"
      placeholder: |
        com.example.firstapp
        com.example.secondapp
        com.example.thirdapp

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Optional: Any extra details about the icon requests."
