name: "Icon Improvement Request"
description: "Submit requests for improving existing icons, including proposed design images."
title: "Icon Improvement Request:"
labels: ["icon improvement"]
type: form
body:
  - type: input
    id: app_names
    attributes:
      label: "Application Names"
      description: "Enter the names of the applications whose icons you want to improve, separated by commas."
      placeholder: "YouTube, Netflix, Prime Video"

  - type: file
    id: image_files
    attributes:
      label: "Proposed Icon Images"
      description: "Upload one or more high-quality images of the improved icons. Ensure they are clear and sharp. Requests require at least one image to be provided."
      multiple: true
