name: Icon Request
description: Submit a request for an application icon compatible with TV devices.
title: Icon Request
labels: icon-request
body:
  - type: input
    id: app_name
    attributes:
      label: Application Name
      description: Enter the name of the app you want an icon for.
    validation:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other information that may help create the icon.
